const productosArray = [
    {nombre: "Future State Aquaman #1", precio: 445, img: "../img/dc/Future-State-Aquaman-1-2021.jpg", posicion: 1, id: 1},
    {nombre: "Future State Aquaman #2", precio: 454, img: "../img/dc/Future-State-Aquaman-2-2021.jpg", posicion: 1, id: 2},
    {nombre: "Future State Batman Superman #1", precio: 345, img: "../img/dc/Future-State-Batman-Superman-1-2021.jpg", posicion: 1, id: 3},
    {nombre: "Future State Batman Superman #2", precio: 456, img: "../img/dc/Future-State-Batman-Superman-2-2021.jpg", posicion: 1, id: 4},
    {nombre: "Future State Catwoman #1", precio: 334, img: "../img/dc/Future-State-Catwoman-1-2021.jpg", posicion: 1, id: 5},
    {nombre: "Future State Catwoman #2", precio: 387, img: "../img/dc/Future-State-Catwoman-2-2021.jpg", posicion: 1, id: 6},
    {nombre: "Future State Dark Detective #1", precio: 453, img: "../img/dc/Future-State-Dark-Detective-1-2021.jpg", posicion: 1, id: 7},
    {nombre: "Future State Dark Detective #2", precio: 444, img: "../img/dc/Future-State-Dark-Detective-2-2021.jpg", posicion: 1, id: 8},
    {nombre: "Future State Dark Detective #3", precio: 475, img: "../img/dc/Future-State-Dark-Detective-3-2021.jpg", posicion: 1, id: 9},
    {nombre: "Future State Dark Detective #4", precio: 483, img: "../img/dc/Future-State-Dark-Detective-4-2021.jpg", posicion: 1, id: 10},
    {nombre: "Future State Gotham #1", precio: 400, img: "../img/dc/Future-State-Gotham-1-2021.jpg", posicion: 1, id: 11},
    {nombre: "Future State Gotham #2", precio: 435, img: "../img/dc/Future-State-Gotham-2-2021.jpg", posicion: 1, id: 12},
    {nombre: "Future State Gotham #3", precio: 490, img: "../img/dc/Future-State-Gotham-3-2021.jpg", posicion: 2, id: 13},
    {nombre: "Future State Gotham #4", precio: 344, img: "../img/dc/Future-State-Gotham-4-2021.jpg", posicion: 2, id: 14},
    {nombre: "Future State Gotham #5", precio: 399, img: "../img/dc/Future-State-Gotham-5-2021.jpg", posicion: 2, id: 15},
    {nombre: "Future State Green Lantern #1", precio: 496, img: "../img/dc/Future-State-Green-Lantern-1-2021.jpg", posicion: 2, id: 16},
    {nombre: "Future State Green Lantern #2", precio: 434, img: "../img/dc/Future-State-Green-Lantern-2-2021.jpg", posicion: 2, id: 17},
    {nombre: "Future State Harley Quinn #1", precio: 482, img: "../img/dc/Future-State-Harley-Quinn-1-2021.jpg", posicion: 2, id: 18},
    {nombre: "Future State Harley Quinn #2", precio: 344, img: "../img/dc/Future-State-Harley-Quinn-2-2021.jpg", posicion: 2, id: 19},
    {nombre: "Future State Immortal Wonder Woman #1", precio: 367, img: "../img/dc/Future-State-Immortal-Wonder-Woman-1-2021.jpg", posicion: 2, id: 20},
    {nombre: "Future State Immortal Wonder Woman #2", precio: 359, img: "../img/dc/Future-State-Immortal-Wonder-Woman-2-2021.jpg", posicion: 2, id: 21},
    {nombre: "Future State Justice League #1", precio: 499, img: "../img/dc/Future-State-Justice-League-1-2021.jpg", posicion: 2, id: 22},
    {nombre: "Future State Justice League #2", precio: 499, img: "../img/dc/Future-State-Justice-League-2-2021.jpg", posicion: 2, id: 23},
    {nombre: "Future State Kara Zor-El Superwoman #1", precio: 432, img: "../img/dc/Future-State-Kara-Zor-El-Superwoman-1-2021.jpg", posicion: 2, id: 24},
    {nombre: "Future State Kara Zor-El Superwoman #2", precio: 333, img: "../img/dc/Future-State-Kara-Zor-El-Superwoman-2-2021.jpg", posicion: 3, id: 25},
    {nombre: "Future State Legion of Super Heroes #1", precio: 322, img: "../img/dc/Future-State-Legion-of-Super-Heroes-1-2021.jpg", posicion: 3, id: 26},
    {nombre: "Future State Legion of Super Heroes #2", precio: 310, img: "../img/dc/Future-State-Legion-of-Super-Heroes-2-2021.jpg", posicion: 3, id: 27},
    {nombre: "Future State Nightwing #1", precio: 323, img: "../img/dc/Future-State-Nightwing-1-2021.jpg", posicion: 3, id: 28},
    {nombre: "Future State Nightwing #2", precio: 359, img: "../img/dc/Future-State-Nightwing-2-2021.jpg", posicion: 3, id: 29},
    {nombre: "Future State Robin Eternal #1", precio: 349, img: "../img/dc/Future-State-Robin-Eternal-1-2021.jpg", posicion: 3, id: 30},
    {nombre: "Future State Robin Eternal #2", precio: 349, img: "../img/dc/Future-State-Robin-Eternal-2-2021.jpg", posicion: 3, id: 31},
    {nombre: "Future State Shazam #1", precio: 394, img: "../img/dc/Future-State-Shazam-1-2021.jpg", posicion: 3, id: 32},
    {nombre: "Future State Shazam #2", precio: 384, img: "../img/dc/Future-State-Shazam-2-2021.jpg", posicion: 3, id: 33},
    {nombre: "Future State Suicide Squad #1", precio: 412, img: "../img/dc/Future-State-Suicide-Squad-1-2021.jpg", posicion: 3, id: 34},
    {nombre: "Future State Suicide Squad #2", precio: 433, img: "../img/dc/Future-State-Suicide-Squad-2-2021.jpg", posicion: 3, id: 35},
    {nombre: "Future State Superman House of El #1", precio: 329, img: "../img/dc/Future-State-Superman-House-of-El-1-2021.jpg", posicion: 3, id: 36},
    {nombre: "Future State Superman of Metropolis #1", precio: 399, img: "../img/dc/Future-State-Superman-of-Metropolis-1-2021.jpg", posicion: 4, id: 37},
    {nombre: "Future State Superman of Metropolis #2", precio: 399, img: "../img/dc/Future-State-Superman-of-Metropolis-2-2021.jpg", posicion: 4, id: 38},
    {nombre: "Future State Superman vs. Imperious Lex #1", precio: 323, img: "../img/dc/Future-State-Superman-vs.-Imperious-Lex-1-2021.jpg", posicion: 4, id: 39},
    {nombre: "Future State Superman vs. Imperious Lex #2", precio: 359, img: "../img/dc/Future-State-Superman-vs.-Imperious-Lex-2-2021.jpg", posicion: 4, id: 40},
    {nombre: "Future State Superman vs. Imperious Lex #3", precio: 358, img: "../img/dc/Future-State-Superman-vs.-Imperious-Lex-3-2021.jpg", posicion: 4, id: 41},
    {nombre: "Future State Superman Wonder Woman #1", precio: 311, img: "../img/dc/Future-State-Superman-Wonder-Woman-1-2021.jpg", posicion: 4, id: 42},
    {nombre: "Future State Superman Wonder Woman #2", precio: 411, img: "../img/dc/Future-State-Superman-Wonder-Woman-2-2021.jpg", posicion: 4, id: 43},
    {nombre: "Future State Superman Worlds of War #1", precio: 403, img: "../img/dc/Future-State-Superman-Worlds-of-War-1-2021.jpg", posicion: 4, id: 44},
    {nombre: "Future State Superman Worlds of War #2", precio: 400, img: "../img/dc/Future-State-Superman-Worlds-of-War-2-2021.jpg", posicion: 4, id: 45},
    {nombre: "Future State Swamp Thing #1", precio: 311, img: "../img/dc/Future-State-Swamp-Thing-1-2020.jpg", posicion: 4, id: 46},
    {nombre: "Future State Swamp Thing #2", precio: 330, img: "../img/dc/Future-State-Swamp-Thing-2-2021.jpg", posicion: 4, id: 47},
    {nombre: "Future State Teen Titans #1", precio: 334, img: "../img/dc/Future-State-Teen-Titans-1-2021.jpg", posicion: 4, id: 48},
    {nombre: "Future State Teen Titans #2", precio: 309, img: "../img/dc/Future-State-Teen-Titans-2-2021.jpg", posicion: 5, id: 49},
    {nombre: "Future State Teen Titans Ruins #1", precio: 454, img: "../img/dc/Future-State-Teen-Titans-Ruins-1-2021.jpg", posicion: 5, id: 50},
    {nombre: "Future State The Flash #1", precio: 445, img: "../img/dc/Future-State-The-Flash-1-2020.jpg", posicion: 5, id: 51},
    {nombre: "Future State The Flash #2", precio: 469, img: "../img/dc/Future-State-The-Flash-2-2021.jpg", posicion: 5, id: 52},
    {nombre: "Future State The Next Batman #1", precio: 456, img: "../img/dc/Future-State-The-Next-Batman-1-2020.jpg", posicion: 5, id: 53},
    {nombre: "Future State The Next Batman #2", precio: 450, img: "../img/dc/Future-State-The-Next-Batman-2-2021.jpg", posicion: 5, id: 54},
    {nombre: "Future State The Next Batman #3", precio: 490, img: "../img/dc/Future-State-The-Next-Batman-3-2021.jpg", posicion: 5, id: 55},
    {nombre: "Future State The Next Batman #4", precio: 498, img: "../img/dc/Future-State-The-Next-Batman-4-2021.jpg", posicion: 5, id: 56},
    {nombre: "Future State Wonder Woman #1", precio: 344, img: "../img/dc/Future-State-Wonder-Woman-1-2020.jpg", posicion: 5, id: 57},
    {nombre: "Future State Wonder Woman #2", precio: 396, img: "../img/dc/Future-State-Wonder-Woman-2-2021.jpg", posicion: 5, id: 58}
]